version: '3.0'
services:
  rasa:
    image: rasa/rasa:1.10.11-full
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run
  actionserver:
    image: Balowen/rasabot:latest
    expose: 5055